### ISSUE TITLE
latest update is not working properly 0.10.10

### ISSUE THREAD

**Issue by attarawnneh** [thepotterfamily/homebridge-ewelink-beta#1]
TypeError: Cannot read property 'updateCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:538:78
    at Map.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:347:41
    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request/request.js:1083:12)

**Comment by thepotterfamily** [comment]
hi, have you refreshed your homebridge cache?

**Comment by attarawnneh** [comment]
yes! an I had to do a fresh copy of the RP server and yet still receiving the same issue, I lost everything! :(


TypeError: Cannot read property 'updateCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:538:78
    at Map.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:347:41
    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-beta/node_modules/request/request.js:1083:12)

**Comment by thepotterfamily** [comment]
Please can I ask which sonoff devices you have?
With this package the name is in the title “beta” so it’s not going to be perfect.
And by perfect i mean - probably bugs.
But i’d love to work with you to test your devices and improve this package.

**Comment by attarawnneh** [comment]
yes I know, definitely nothing is perfect my friend, and your work is awesome; but the version before this one was just perfect, if you can guid me to install that one it would much appreciated. 
I would love to support with anything that you need.
I have wall units tc2 and tc3
I have motion sensor with sonoff bridge and temperature sensor as well.

**Comment by thepotterfamily** [comment]
Please email me bwp91@icloud.com

**Comment by thepotterfamily** [comment]
should be sorted now due to your help on the matter @attarawnneh.
thanks again!
