### ISSUE TITLE
Error starting homebridge

### ISSUE THREAD

**Issue by blackswanza** [thepotterfamily/homebridge-ewelink-beta#6]
7/7/2020, 17:13:57] Loaded plugin: homebridge-harmony@1.3.12
[7/7/2020, 17:13:57] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[7/7/2020, 17:13:57] ---
[7/7/2020, 17:13:58] Loaded plugin: homebridge-lgwebos-tv@1.0.0
[7/7/2020, 17:13:58] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[7/7/2020, 17:13:58] ---
[7/7/2020, 17:13:59] Loaded plugin: homebridge-tplink-smarthome@5.1.0
[7/7/2020, 17:13:59] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[7/7/2020, 17:13:59] ---
[7/7/2020, 17:13:59] Loading 5 platforms...
[7/7/2020, 17:13:59] [Config] Initializing config platform...
[7/7/2020, 17:13:59] [Config] Running in Service Mode
[7/7/2020, 17:13:59] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[7/7/2020, 17:13:59] [TplinkSmarthome] homebridge-tplink-smarthome v5.1.0, node v12.18.1, homebridge v1.1.1
[7/7/2020, 17:14:00] [LgWebOsTv] Initializing LgWebOsTv platform...
[7/7/2020, 17:14:00] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[7/7/2020, 17:14:00] [Harmony Hub] HarmonyPlatform Init
[7/7/2020, 17:14:00] Error loading platform requested in your config.json at position 5
[7/7/2020, 17:14:02] Error: The requested platform 'eWeLink' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[7/7/2020, 17:14:02] Got SIGTERM, shutting down Homebridge...
[7/7/2020, 17:14:02] [Harmony Hub] INFO - shutdown
[7/7/2020, 17:14:07] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/7/2020, 17:14:12] [HB Supervisor] Restarting Homebridge...

**Comment by thepotterfamily** [comment]
Hi, just checking this out now

**Comment by thepotterfamily** [comment]
Can you show me the previous few lines of logs?

**Comment by blackswanza** [comment]
[7/7/2020, 17:29:43] [Config] Running Command: sudo -E -n npm install homebridge-ewelink-beta@latest
[7/7/2020, 17:30:03] [TplinkSmarthome.API] TCP 192.168.1.252:9999 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[7/7/2020, 17:30:03] [TplinkSmarthome] [Computer Room] emeter.getRealtime()
[7/7/2020, 17:30:03] [TplinkSmarthome] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[7/7/2020, 17:31:27] [Config] Changes to config.json saved.
[7/7/2020, 17:31:35] [Config] Homebridge restart request received
[7/7/2020, 17:31:35] [Config] UI / Bridge settings have not changed; only restarting Homebridge process
[7/7/2020, 17:31:35] [HB Supervisor] Sending SIGTERM to Homebridge
[7/7/2020, 17:31:35] Got SIGTERM, shutting down Homebridge...
[7/7/2020, 17:31:35] [Harmony Hub] INFO - shutdown
[7/7/2020, 17:31:41] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/7/2020, 17:31:46] [HB Supervisor] Restarting Homebridge...
[7/7/2020, 17:31:46] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/7/2020, 17:31:46] [HB Supervisor] Started Homebridge v1.1.1 with PID: 1461
[7/7/2020, 17:32:07] Loaded config.json with 0 accessories and 5 platforms.
[7/7/2020, 17:32:07] ---
[7/7/2020, 17:32:19] Loaded plugin: homebridge-config-ui-x@4.23.2
[7/7/2020, 17:32:19] Registering platform 'homebridge-config-ui-x.config'
[7/7/2020, 17:32:19] ---
[7/7/2020, 17:32:20] ====================
[7/7/2020, 17:32:20] ERROR LOADING PLUGIN homebridge-ewelink-beta:
[7/7/2020, 17:32:20] Error: Cannot find module './src/constants'
Require stack:
- /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
[7/7/2020, 17:32:20] ====================
[7/7/2020, 17:32:29] Loaded plugin: homebridge-harmony@1.3.12
[7/7/2020, 17:32:29] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[7/7/2020, 17:32:29] ---
[7/7/2020, 17:32:30] Loaded plugin: homebridge-lgwebos-tv@1.0.0
[7/7/2020, 17:32:30] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[7/7/2020, 17:32:30] ---
[7/7/2020, 17:32:31] Loaded plugin: homebridge-tplink-smarthome@5.1.0
[7/7/2020, 17:32:31] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[7/7/2020, 17:32:31] ---
[7/7/2020, 17:32:31] Loading 5 platforms...
[7/7/2020, 17:32:32] [Config] Initializing config platform...
[7/7/2020, 17:32:32] [Config] Running in Service Mode
[7/7/2020, 17:32:32] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[7/7/2020, 17:32:32] [TplinkSmarthome] homebridge-tplink-smarthome v5.1.0, node v12.18.1, homebridge v1.1.1
[7/7/2020, 17:32:32] [LgWebOsTv] Initializing LgWebOsTv platform...
[7/7/2020, 17:32:32] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[7/7/2020, 17:32:32] [Harmony Hub] HarmonyPlatform Init
[7/7/2020, 17:32:32] Error loading platform requested in your config.json at position 5
[7/7/2020, 17:32:34] Error: The requested platform 'eWeLink' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[7/7/2020, 17:32:34] Got SIGTERM, shutting down Homebridge...
[7/7/2020, 17:32:35] [Harmony Hub] INFO - shutdown
[7/7/2020, 17:32:40] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/7/2020, 17:32:45] [HB Supervisor] Restarting Homebridge...

**Comment by thepotterfamily** [comment]
Please try updating to v1.7.2 and that should fix it. 
Let me know!
Thanks

**Comment by blackswanza** [comment]
It Startup this time but now getting this error.

[7/7/2020, 17:42:53] [eWeLink] [0] eWeLink devices were loaded from the Homebridge cache.
[7/7/2020, 17:42:53] [eWeLink] [1] primary devices were loaded from your eWeLink account.
[7/7/2020, 17:42:53] [eWeLink] [0] custom groups were loaded from the configuration.
(node:2135) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'chansFromUiid' of undefined
    at eWeLink.addAccessory (/usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:457:111)
    at /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:151:40
    at Map.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ewelink-beta/index.js:103:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2135) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2135) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by thepotterfamily** [comment]
Please try v1.7.3 😅

**Comment by blackswanza** [comment]
Cool its working 100%. Thanks
